server:
  port: 9000

spring:
  datasource:
    username: root
    password: Jiabinbin34...
    url: jdbc:mysql://47.101.163.13:3306/blog_dev?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:/com/blog/main/mapper/*Mapper.xml
logging:
  config: classpath:log4j2.yml